### ISSUE TITLE
Need support for Custom Fields

### ISSUE THREAD

**Issue by pm7y** [loveleif/AnotherJiraRestClient#10]
Would be great to have supported for custom fields. Perhaps make Fields class a partial and this could be added as needed.

**Comment by cmawhorter** [comment]
I know this is old but I've been using this:

`newIssue.AddField("customfield_10024", "my custom value");`

That's `customfield_` and the custom field ID, which can be found in your admin.

**Comment by loveleif** [comment]
Thanks @cmawhorter! And I'm sorry for the limited support I've been able to give.
